### ISSUE TITLE
update maskdino init method

### ISSUE THREAD

**Issue by kaiguy23** [IDEACVR/MaskDINO#21]
The following lines need to be removed from `__init__.py ` in the maskdino/ folder:
`from .data.dataset_mappers.mask_former_instance_dataset_mapper import (
    MaskFormerInstanceDatasetMapper,
)
`
`
from .data.dataset_mappers.mask_former_panoptic_dataset_mapper import (
    MaskFormerPanopticDatasetMapper,
)`
These modules were removed in the latest commits.

**Comment by FengLi-ust** [comment]
Thanks, I have updated these lines.
