### ISSUE TITLE
About implementation details

### ISSUE THREAD

**Issue by zen-star** [IDEACVR/MaskDINO#3]
Thanks for your impressive work first!
I'd like to dive into some details:

---

> We predict both boxes and masks in the encoder and select the top-ranked ones to initialize decoder queries.

As far as I know, the feature sequence is lengthy (128x128+64x64+32x32+16x16 for 4-scale ). If each feature vector predicts its mask prediction (with reso. 256x256), it is very likely to consume too much GPU memory. Could you please elaborate on the implementation? 

---

> initialize both the content and anchor box queries in Mask DINO

Does it behave like 2-stage Deformable DETR ( _q, q_pos = split( LN(Linear(PE(bbox))), edims )_ ) ? Or something else?

**Comment by SuperHenry2333** [comment]
We are sorry that the expression "We predict both boxes and masks in the encoder and select the top-ranked ones to initialize decoder queries." may be confusing.  We actually select tokens that have high classification scores and only calculate masks with selected tokens. Yes, it is similar to 2-stage Deformable DETR.

**Comment by zen-star** [comment]
Thank you for your clear and helpful answer^^

**Comment by 1338199** [comment]
So how to use the predicted masks and boxes to initialize the anchors in unified query selection?
