### ISSUE TITLE
About mask head on eq 1

### ISSUE THREAD

**Issue by oxpie** [IDEACVR/MaskDINO#6]
About eq (1) below where the paper say that "M is the segmentation head", does it mean there is an extra layer operating over the 2d map `T(Cb) + F(Ce)`? If so, what kind of layer is it? Intuitively, I would expect an MLP layer over `qc` instead.

`m = qc ⊗ M(T(Cb) + F(Ce))`

Thank you!

**Comment by FengLi-ust** [comment]
It is a feature transformation layer, a simple convlution layer should work.

**Comment by oxpie** [comment]
Thanks!
