### ISSUE TITLE
RuntimeWarning: invalid value encountered in intersection on my custom dataset

### ISSUE THREAD

**Issue by Ulteraa** [IDEACVR/MaskDINO#61]
Hello,
I am training maskDINO on my own dataset and I get:

"lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection". 

would it create an issue or it is ok and the model will be trained correctly?

thanks

**Comment by FengLi-ust** [comment]
I am not sure. Is everything going well in your training?

**Comment by Ulteraa** [comment]
Hi FengLi,
I hope you are doing well and thank you for your response. Yes, the training was done properly. This warning happens because in some of images in tmy dataset there is not objects that I am looking for.

**Comment by William-Yao-2000** [comment]
I meet this issue too. It seems that the model training is done properly. So I just ignore this RuntimeWarning by adding a line in the train_net.py:
(starts from line 9)
```
try:
    from shapely.errors import ShapelyDeprecationWarning
    import warnings
    warnings.filterwarnings('ignore', category=ShapelyDeprecationWarning)
    warnings.filterwarnings('ignore', category=RuntimeWarning)
except:
    pass
```

**Comment by Ulteraa** [comment]
Hi well i think in this case you only get rid of warning message but maybe you need to revise your code to make sure that something wired does not happen in your training pipeline.

**Comment by Ulteraa** [comment]
> I meet this issue too. It seems that the model training is done properly. So I just ignore this RuntimeWarning by adding a line in the train_net.py: (starts from line 9)
> 
> ```
> try:
>     from shapely.errors import ShapelyDeprecationWarning
>     import warnings
>     warnings.filterwarnings('ignore', category=ShapelyDeprecationWarning)
>     warnings.filterwarnings('ignore', category=RuntimeWarning)
> except:
>     pass
> ```

Hi well i think in this case you only get rid of warning message but maybe you need to revise your code to make sure that something wired does not happen in your training pipeline.

**Comment by William-Yao-2000** [comment]
> > I meet this issue too. It seems that the model training is done properly. So I just ignore this RuntimeWarning by adding a line in the train_net.py: (starts from line 9)
> > ```
> > try:
> >     from shapely.errors import ShapelyDeprecationWarning
> >     import warnings
> >     warnings.filterwarnings('ignore', category=ShapelyDeprecationWarning)
> >     warnings.filterwarnings('ignore', category=RuntimeWarning)
> > except:
> >     pass
> > ```
> 
> Hi well i think in this case you only get rid of warning message but maybe you need to revise your code to make sure that something wired does not happen in your training pipeline.

Yeah I agree with you. I haven't finished reading the code. Do you know which part of code causes the warning?
btw, I find a issue which is almost as same as this one: #https://github.com/facebookresearch/Mask2Former/issues/171#issue-1535705440

**Comment by Ulteraa** [comment]
> > > I meet this issue too. It seems that the model training is done properly. So I just ignore this RuntimeWarning by adding a line in the train_net.py: (starts from line 9)
> > > ```
> > > try:
> > >     from shapely.errors import ShapelyDeprecationWarning
> > >     import warnings
> > >     warnings.filterwarnings('ignore', category=ShapelyDeprecationWarning)
> > >     warnings.filterwarnings('ignore', category=RuntimeWarning)
> > > except:
> > >     pass
> > > ```
> > 
> > 
> > Hi well i think in this case you only get rid of warning message but maybe you need to revise your code to make sure that something wired does not happen in your training pipeline.
> 
> Yeah I agree with you. I haven't finished reading the code. Do you know which part of code causes the warning? btw, I find a issue which is almost as same as this one: #[facebookresearch/Mask2Former#171 (comment)](https://github.com/facebookresearch/Mask2Former/issues/171#issue-1535705440)

As far as I remember it was related to one package in Python dealing with geometry (bounding box and computing the IOU) , probably this metric  produce a NAN during the training.
